version: '3.9'

services:
  # ------------------ PostgreSQL cho Auth ------------------
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  # ------------------ Auth Service ------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres-auth
    env_file:
      - ./auth-service/.env         
    volumes:
      - ./auth-service:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start:dev

volumes:
  auth_pgdata:
