global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:3000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3000']
